In [11]:
import numpy as np

X_ = np.array([[-1., -2.], [-1, -3]])
W_ = np.array([[1., -3], 
               [1., -3]])
b_ = np.array([-3., -5])

In [12]:
X_

array([[-1., -2.],
       [-1., -3.]])

In [13]:
W_

array([[ 1., -3.],
       [ 1., -3.]])

In [14]:
print( np.dot(X_,W_))

[[ -3.   9.]
 [ -4.  12.]]
